### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by xbelanch** [maca134/Maca134.Arma.DllExport#3]
After reading this tutorial (https://forums.bistudio.com/forums/topic/210259-arma-dllexport-c-extensions/) I tried this but I don't figure out how it works on Arma3 once .dll is loaded. If I have this code: 

```
using Maca134.Arma.DllExport;

namespace A3Extension
{
    public class DllEntry
    {
        [ArmaDllExport]
        public static string Invoke(string input, int size)
        {
            return input;
        }
    }
}
```
I executed this command from the EDC on Arma `A3Extension callExtension "Invoke"` but nothing happens... also `A3Extension callExtension ["Invoke", ["Hello"]]` but the same result. 

Any advice?

**Comment by maca134** [comment]
if your running 64 bit arma, the extension needs to be called extname_x64.dll

**Comment by xbelanch** [comment]
Renamed to extname_x64.dll but still doesn't work. I put the .dll in the Arma3 root folder (I know you don't recommended that way).  I'm sure that it's a stupid little thing, but I can't see it.

**Comment by maca134** [comment]
im sure it works as i used recently for an extension to for extracting heightmaps from arma.

**Comment by xbelanch** [comment]
in .rpt file: 22:40:47 Call extension 'A3Extension' could not be loaded: Recursos insuficientes en el sistema para completar el servicio solicitado. (english translation: "insuficient resources on the system to complete the solicited service (?))

**Comment by xbelanch** [comment]
I think I found the issue: disabling Battleye the extension works. On the other hand I recorded a screencast of every step I made if it could be hepful to you.

https://www.youtube.com/watch?v=ahbPNf-Q_Qs
