### ISSUE TITLE
Error: you can only have 1 method with the attribute ArmaDllExportAttribute

### ISSUE THREAD

**Issue by Bluscream** [maca134/Maca134.Arma.DllExport#5]
Why is that? can't i call multiple methods by name from within ArmA?

**Comment by maca134** [comment]
an arma extension only has 1 entry point, so no you can not define multiple entry points

**Comment by Bluscream** [comment]
so you would need one dll **per** function you want to call from within arma? that sounds weird

**Comment by maca134** [comment]
you route commands in the dll

**Comment by Bluscream** [comment]
Can you give an example of what you mean?

**Comment by maca134** [comment]
no sorry
